"""Creative adapter error taxonomy."""

ERROR_CODES = ('ENV_NOT_FOUND', 'SERVICE_UNAVAILABLE', 'LICENSE_BLOCKED', 'FILE_MISSING', 'ARCHIVE_PART_MISSING', 'ADAPTER_UNSUPPORTED', 'VALIDATION_FAILED', 'PERMISSION_DENIED', 'USER_APPROVAL_REQUIRED', 'LONG_TASK_BLOCKED', 'PRIVATE_ASSET_NOT_COMMITTABLE', 'LOCAL_PATH_LEAK_BLOCKED', 'LARGE_FILE_BLOCKED', 'EXTERNAL_ADOPTION_NOT_CONFIRMED', 'UNSAFE_DESTRUCTIVE_ACTION_BLOCKED', 'RELEASE_GATE_FAILED', 'DEMO_ASSET_UNSAFE', 'QUICKSTART_FAILED', 'DOCS_INCOMPLETE', 'HEALTH_METRIC_REGRESSION')
